Carbon:
  IncludeAssets:
    Packages:
      'Jonnitto.PrettyEmbedHelper':
        Package: 'Jonnitto.PrettyEmbedHelper'
        ConditionPrototype: 'Jonnitto.PrettyEmbedHelper:IncludeAssets'
        Path:
          Inline:
              CSS: Private/Templates/InlineAssets
              JS: Private/Templates/InlineAssets
              MJS: Private/Templates/InlineAssets
              HTML: Private/Templates/InlineAssets
          File:
              CSS: Public/Styles
              JS: Public/Scripts
              MJS: Public/Modules
              PRELOADASSET: Public/Assets
              PRELOADCSS: Public/Styles
              PRELOADSCRIPT: Public/Scripts
              MODULEPRELOAD: Public/Modules
        General:
          Head: Main.css
        Backend:
          Head:
            - Backend.css
            - Backend.js[defer]
        Live:
          Head: Main.js[defer]
