Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.PrettyEmbedHelper:
            - 'NodeTypes/*'
    nodeTypes:
      groups:
        prettyembed:
          position: 200
          label: 'Jonnitto.PrettyEmbedHelper:NodeTypes.Mixin.Groups:prettyembed'
    fusion:
      autoInclude:
        Jonnitto.PrettyEmbedHelper: true
  Fusion:
    defaultContext:
      Jonnitto.PrettyEmbedHelper: 'Jonnitto\PrettyEmbedHelper\Eel\Helper'
